config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  resources :cards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :player do
    root to: "devise/sessions#new"
  end

  resources :players do
    resources :decks
    resources :collection
    resources :battle do
      get "room", to: 'battle#show'
      mount ActionCable.server => "/cable"
    end
  end
  
  get '/deck/:deck_id', to: 'decks#deckdata'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :card_copies

  def url
    region = 'sa-east-1'
    s3 = Aws::S3::Resource.new(region: region)
    card_bucket = s3.bucket('cards-images')
    card_bucket.object(card_image).presigned_url(:get)
  end
end

app/models/card_copy.rb
class CardCopy < ApplicationRecord
  has_many :card_decks
  belongs_to :player
  belongs_to :card
  
  def data
    Card.find(card_id)
  end
end

app/models/card_deck.rb
class CardDeck < ApplicationRecord
  belongs_to :deck
  belongs_to :card_copy
  
  def data
    CardCopy.find(card_copy_id).data
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :player
  has_many :card_decks
  
  def list_of_cards
    CardDeck.where(deck_id: id).map(&:data)
  end
end

app/models/game.rb
class Game
  def self.start(current_player1, current_player2)
    first, second = [current_player1.to_s, current_player2].shuffle

    Game.set_players(first,second)

    Game.msg_player('first', "game_start", "You are going first")
    Game.msg_player('second', "game_start", "You are going second")

    REDIS.set("opponent_for:#{first}", second)
    REDIS.set("opponent_for:#{second}", first)
  end

  def self.set_players(p1,p2)
    REDIS.set("first", p1)
    REDIS.set("second", p2)
  end

  def self.get_players
    first = REDIS.get("first")
    second = REDIS.get("second")
    [first, second]
  end

  def self.msg_player(player,action,msg)
    player = REDIS.get("#{player}")
    ActionCable.server.broadcast "player_#{player}", {action: action, msg: msg}
  end

  def self.msg_both(action, msg)
    arr = Game.get_players
    arr.map do |player_id|
      ActionCable.server.broadcast "player_#{player_id}", {action: action, msg: msg}
    end
  end

  def self.opponent_for(current_player)
    REDIS.get("opponent_for:#{current_player}")
  end

  def self.speak(data)
    Game.msg_both("speak", data['msg'])
  end

  def self.load_decks
    players = Game.get_players
    decks = []
    players.each do |player_id|
      deck = Game.deck(player_id)
      decks.push(deck)
    end
    Game.msg_both('load_deck', decks)
    #
    #
    # player1 = REDIS.get("first")
    # deck1 = Game.deck(player1)
    # player2 = REDIS.get("second")
    # deck2 = Game.deck(player2)
    #
    # Game.msg_both('load_deck', deck2)

  end

  def self.deck(player)
    player_id = REDIS.get("#{player}")
    player = Player.find(player_id)
    deck = player.deck.map do |card|
      card_obj = card.card_copy.card
      card_data = card_obj.serializable_hash
      card_data['temp_url'] = card_obj.url
      card_data
    end
    deck
  end

  # def self.card(card_obj)
  #     card_data = card_obj.serializable_hash
  #     card_data['temp_url'] = card_obj.url
  #     card_data
  # end
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :decks
         has_many :card_copies

  def deck
    Deck.where(player_id: id).first.card_decks
  end
  def decks
    Deck.where(player_id: id)
  end
end

app/models/seek.rb
class Seek
  def self.create(player)
    if opponent = REDIS.spop("seeks")
      Game.start(player.id,opponent)
    else
      REDIS.sadd("seeks", player.id)
    end
  end

  def self.remove(player)
    REDIS.srem("seeks", player)
  end

  def self.clear_all
    REDIS.del("seeks")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :authenticate_player!
    before_action :cookie_set

   def cookie_set
       @user = current_player
       return unless current_player
       cookies.signed[:player_id] = @user.id
     end
  protected

  def after_sign_in_path_for(resource)
  "/players/#{resource.id}"
  end

end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
  def index

  end

  def show

  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
  	@cards = Card.all
  end
  def new
  	@card = Card.new()
  end
  def create
  	Card.create!(card_params)
  end
  def show
    @card = Card.find(params[:id])
  end
  private
 	def card_params
 		params.require(:card).permit(:name, :klass, :rarity, :mana_cost, :type_of_card, :collection, :collection_number, :skills, :attack, :hp)
 	end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  def index
    @cards = Card.all
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @cards = CardCopy.where(player_id: params[:player_id])
    @decks = Player.find(params[:player_id]).decks
  end
  
  def deckdata
    deck = Deck.find(params[:deck_id])
    cards = deck.list_of_cards.map(&:url)
    render json: {:payload => cards}.to_json 
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/battle/index.html.erb
<%= link_to "ROOM 1", "battle/room" %>

app/views/battle/show.html.erb
<%= javascript_include_tag 'game' %>

<div id="msg">

</div>

<%= render "layouts/board" %>

app/views/cards/index.html.erb
<div class="mx-auto table">
	<table>
	<tr>
		<th>N.</th>
		<th>Name</th>
		<th>Class</th>
		<th>Type of card</th>
		<th colspan="2">Collection</th>
		<th>Healt points</th>
		<th>Attack points</th>
		<th>Skills</th>
		<!-- <th>Card</th> -->

	</tr>
	<% @cards.each do |card|%>
	<tr>
		<td><%= card.id%></td>
		<td><%= card.name%></td>
		<td><%= card.klass%></td>
		<td><%= card.kingdom%></td>
		<td><%= card.collection%></td>
		<td><%= card.collection_number%></td>
		<td><%= card.hp%></td>
		<td><%= card.attack%></td>
		<td><%= card.skills%></td>
		<!-- <td><%= image_tag asset_path(card.card_image)%></td> -->
	</tr>
	<%end%>
</table>

<div style="width:100%;border:1px solid black;height: 400px;"class="">

</div>

app/views/cards/new.html.erb
	<%= form_for @card, url: {action: 'create'}, html: { class: "form-group" }  do |form| %>

			 <div class="form-inline">
					 <label>Name:</label>
					 <%= form.text_field :name, class: 'form-control' %>
				 </div>
			 <div class="form-inline">
				 <label>Rarity:</label>
				 <%= form.text_field :rarity, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Class:</label>
				 <%= form.text_field :klass, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Kingdom:</label>
				 <%= form.text_field :kingdom, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Collection:</label>
				 <%= form.text_field :collection, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Collection number:</label>
				 <%= form.number_field :collection_number, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Health points:</label>
				 <%= form.number_field :hp, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Attack points:</label>
				 <%= form.number_field :attack, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Skills:</label>
				 <%= form.text_field :skills, class: 'form-control' %>
			 </div>
			 <div class="form-inline">
				 <label>Image:</label>
				 <%= form.text_field :card_image, class: 'form-control' %>
			 </div>
		<%= form.submit "Create" %>
	<%end%>

app/views/cards/show.html.erb
<%= image_tag @card.card_image %>

app/views/collection/index.html.erb
This is your collection


<div class="mx-auto table">
	<table>
	<tr>
		<th>N.</th>
		<th>Name</th>
		<th>Class</th>
		<th>Type of card</th>
		<th >Collection</th>
		<th>Healt points</th>
		<th>Attack points</th>
		<th>Skills</th>
	</tr>
	<% @cards.each do |card|%>
		<tr>
			<td><%= card.id%></td>
			<td><li style="list-style-type: none;" value="<%= card.id%>" data-toggle="modal" data-target="#myModal<%= card.id%>"><%= card.name%></li></td>
			<td><%= card.klass%></td>
			<td><%= card.kingdom%></td>
			<td><%= "#{card.collection}-#{card.collection_number}"%></td>
			<td><%= card.hp%></td>
			<td><%= card.attack%></td>
			<td><%= card.skills%></td>



			<!-- The Modal -->
			<div class="modal fade" id="myModal<%= card.id%>">
				<div class="modal-dialog">
					<div class="modal-content">
						<!-- Modal Header -->
				      <div class="modal-header">
				        <h4 class="modal-title"><%= card.name%></h4>
				        <button type="button" class="close" data-dismiss="modal">&times;</button>
				      </div>

				      <!-- Modal body -->
				      <div class="modal-body mx-auto">
								<%= image_tag card.url, width: '300'%>
				      </div>

				      <!-- Modal footer -->
				      <div class="modal-footer mx-auto">
				       	<%= card.skills%>
				      </div>

					</div>
				</div>
			</div>
		</tr>
	<%end%>

</table>
</div>

app/views/decks/index.html.erb
<nav class="navbar navbar-expand-md bg-light navbar-light">
      <%= link_to "/players/#{current_player.id}" do %>
        <button type="button" class="btn btn-outline-info btn-sm">
            <span >MENU</span>
        </button>
      <%end%>
  <div class="big-title">DECK EDITOR</div>
</nav>
<div>
  <div class="card-view">
    <img class='cardPic' src="" width="300"></img>
  </div>
  <div class="description">
    
  </div>
  <div class="deck">
    <div class="">
      <h6 class="inl">Select a deck:</h6>
      <%= select("deck", "deck_id", @decks.collect {|d| [ d.deck_name, d.id ] }, { include_blank: true }, :onchange => "loadDeck(this.value)")%>
      </div>
      <div class="deck-content">
        
      </div>
  </div>
  <div class="collection">
      <div class="md-title text-center">COLLECTION</div>
        <div class="mx-auto table">
        	<table>
      	    <% @cards.each do |card|%>
      	      <% card = card.data%>
        		  <tr>
        		    <td><%= image_tag card.url, width: '100',onclick: 'addCard(this.src, this.getAttribute("data-id"))', onmousemove: 'cardView(this.src, this.getAttribute("data-skills"))', :data => { :skills => card.skills, :id => card.id}  %></td>
          			<td>
            			 <%= card.name%> <br>
            			 <%= card.kingdom%> <br> 
            			 <%= "HP: #{card.hp}"%> 
            			 <%= "Att: #{card.attack}"%>
          			 </td>
        		  </tr>
      	    <%end%>
        </table>
      </div>
  </div>
</div>

app/views/layouts/_board.html.erb
<div class="gamezone">
  <div class="gameboard">

    <div class="opp-d-g">
      <div class="opp deck-zone">
        <div class="d-z-1">

        </div>
      </div>
      <div class="opp grave-zone">
        <div class="g-z-1">

        </div>
      </div>
    </div>

    <div class="center">
      <div class="opp-side">

        <div class="opp hand-zone">
          <div class="h-z-1">

          </div>
          <div class="h-z-2">

          </div>
          <div class="h-z-3">

          </div>
          <div class="h-z-4">

          </div>
          <div class="h-z-5">

          </div>
        </div>

        <div class="opp mons-zone">
          <div class="m-z-1">

          </div>
          <div class="m-z-2">

          </div>
          <div class="m-z-3">

          </div>
        </div>
      </div>

      <div class="main-side">
        <div class="mons-zone">
          <div class="m-z-1">

          </div>
          <div class="m-z-2">

          </div>
          <div class="m-z-3">

          </div>
        </div>

        <div class="hand-zone">
          <div class="h-z-1">

          </div>
          <div class="h-z-2">

          </div>
          <div class="h-z-3">

          </div>
          <div class="h-z-4">

          </div>
          <div class="h-z-5">

          </div>
        </div>

      </div>
    </div>
    <div class="main-d-g">
      <div class="grave-zone">
        <div class="g-z-1">

        </div>
      </div>
      <div class="deck-zone">
        <div class="d-z-1">

        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardGame</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/players/show.html.erb
<nav class="navbar navbar-expand-md bg-light navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <span><%= "Welcome #{current_player.email}" %></span>
            <span id="header-links" class="col-md"><%= link_to "Logout", destroy_player_session_path, method: :delete, class:"link-design" %></span>
        </li>
    </ul>
</nav>



<div class="btn-mid">
    <%= link_to "#{current_player.id}/decks" do %>
        <button type="button" class="btn btn-outline-info btn-big">
            <span class="big-links">DECKS</span>
        </button>
    <%end%>
</div>
<div class="btn-mid">
    <%= link_to "#{current_player.id}/collection" do %>
        <button type="button" class="btn btn-outline-info btn-big">
            <span class="big-links">COLLECTION</span>
        </button>
    <%end%>
</div>
<div class="btn-mid">
    <%= link_to "#{current_player.id}/battle" do %>
        <button type="button" class="btn btn-outline-info btn-big">
            <span class="big-links">BATTLE</span>
        </button>
    <%end%>
</div>

   

            
            
            
   